# Generated by Django 4.2.27 on 2025-12-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('release_year', models.PositiveIntegerField(verbose_name='Рік виходу')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('director', models.CharField(max_length=100, verbose_name='Режисер')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
            },
        ),
    ]
